version: '3.9'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - "./.srv/database/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - $WORDPRESS_LOCAL_PORT:$WORDPRESS_DOCKER_PORT
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:$MYSQL_DOCKER_PORT
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
      WORDPRESS_DEBUG: $WORDPRESS_DEBUG
    volumes:
      - ./.srv/wordpress/:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/block-theme
      - ./plugin:/var/www/html/wp-content/plugins/theme-core
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini