version: '3.9'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - "./.srv/database/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wp-db
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wp-db
      WORDPRESS_DEBUG: 1
    volumes:
      - ./.srv/wordpress/:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/block-theme
      - ./plugin:/var/www/html/wp-content/plugins/theme-core
      - ./.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini